  name: ft_transcendence
  services:
    frontend:
      container_name: "ff"
      restart: always
      build:
        context: frontend
        target: development
      networks:
        - client-side
      ports:
        - 3000:3000
      volumes:
        - ./frontend/src:/code/src:ro
      env_file:
        - .env
    backend:
      container_name: "bb"
      build:
        args:
        - NODE_ENV=development
        context: backend
        target: dev-envs
      restart: always
      env_file:
      - .env
      ports:
        - 3001:8001
        - 5555:5555
      volumes:
        - ./backend/src:/code/src:rw
        - ./backend/FileRepository:/code/FileRepository:rw
        - ./backend/prisma:/code/prisma:rw
        - ./backend/prisma/migrations:/code/prisma/migrations:rw
        - back-notused:/opt/app/node_modules
      networks:
        - client-side
        - server-side
      depends_on:
        db:
          condition: service_healthy

    db:
      container_name: "dd"
      image: postgres:12-alpine
      restart: always
      env_file:
      - .env
      networks:
        - server-side
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
    
        


  networks:
    client-side: {}
    server-side: {}

  volumes:
    back-notused:
    db-data: {}
