name: ft_transcendence
services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src:ro
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    command: npm run start:dev
    env_file:
    - .env
    ports:
      - 3001:8001
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - client-side
      - server-side
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    env_file:
    - .env
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  back-notused:
  db-data: {}
