version: '3'

services:
  frontend:
    image: node:20
    ports:
      - 3000:3000
    networks:
      app:
        ipv4_address: 10.10.10.2
    working_dir: /app
    volumes:
      - frontlink:/app
    command: bash -c "npm install && npm run dev"
  backend:
    image: node:20
    ports:
      - 3001:3001
    networks:
      app:
        ipv4_address: 10.10.10.3
    working_dir: /back
    volumes:
      - backlink:/back
    command: bash -c "npm install && npm run start:dev"
  database:
    image: postgres:14
    networks:
      app:
        ipv4_address: 10.10.10.4
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
    volumes: 
      - datalink:/var/lib/postgresql/data

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.10.0/24"

volumes:
  frontlink:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/front/app"
  backlink:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/back/app"
  datalink:


